### ISSUE TITLE
Renaming widgets with "macos" prefix

### ISSUE THREAD

**Issue by lesliearkorful** [macosui/macos_ui#107]
All our widget names should start with Mac. eg `MacScaffold`.
This is to prevent name conflicts with existing widgets in the flutter framework and preserve the great developer experience Flutter already has. No dev (yes, including us) dreams of importing our library with a prefix or in every file of their project.

**Comment by GroovinChip** [comment]
I think we should use the `Macos` prefix instead of `Mac`, to keep in line with `MacosApp`, `MacosTheme`, and `MacosThemeData`. And the package name, of course.

**Comment by lesliearkorful** [comment]
Right. I've corrected the title.

**Comment by GroovinChip** [comment]
Reminder that only widgets with overlapping names get the `Macos` prefix. I'll be working on this now.
