### ISSUE TITLE
💡 Sidebar Footer Item 

### ISSUE THREAD

**Issue by ABausG** [macosui/macos_ui#130]
## Use case

It would be nice to be able to provide a footer Widget to the Sidebar of a `MacOSScaffold`.
One example that uses that is the MacApp Store where there is a Profile Summary at the bottom of the sidebar.
Another example is the Apple Calendar App where there is a Month View at the Bottom of the Sidebar

Footer in Mac App Store
<img width="335" alt="Screenshot 2021-06-07 at 14 19 59" src="https://user-images.githubusercontent.com/7288963/121016233-2c7ac100-c79c-11eb-9194-d68075a258dc.png">

Resizing the Window to show Footer Overlapping the Items in the Sidebar
<img width="299" alt="Screenshot 2021-06-07 at 14 20 33" src="https://user-images.githubusercontent.com/7288963/121016242-2e448480-c79c-11eb-9424-0670196a5197.png">

## Proposal
Add a `footer` or `bottom` Parameter to the `Sidebar` Widget. I would propose that this could be of Type `Widget?` to be as flexible as possible.

**Comment by GroovinChip** [comment]
@bdlukaa what do you think? This is definitely a valid use case.

**Comment by GroovinChip** [comment]
FWIW @ABausG I think this is a good feature to add. I see you've already forked the repo - thank you so much for filing this and for taking the initiative to implement the feature!
