### ISSUE TITLE
`MacosScaffold` should not add a `SizedBox` to the top of `Sidebar` 🐛 

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#150]
**Description**

Currently, `MacosScaffold` builds a `SizedBox(height: titleBarHeight - 1),` and adds it to the top of the sidebar. It results in undesired behavior. See the following screenshot:

![Screen Shot 2021-07-12 at 9 57 20 AM](https://user-images.githubusercontent.com/4250470/125299899-8fa9c700-e2f7-11eb-9c14-083a68b8a340.png)

**Steps To Reproduce**

1. Create a new Flutter project and add `macos_ui` to `pubspec.yaml`
2. Replace the contents of `main.dart` with the following:

```dart
import 'package:flutter/material.dart';
import 'package:macos_ui/macos_ui.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MacosApp(
      home: MacosHome(),
    );
  }
}

class MacosHome extends StatelessWidget {
  const MacosHome({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MacosScaffold(
      sidebar: Sidebar(
        minWidth: 200,
        maxWidth: 300,
        builder: (context, scrollController) {
          return Column(
            children: [
              Text('Test'),
            ],
          );
        },
      ),
    );
  }
}
```

**Expected behavior**

The expected behavior is that `Text('Test')` should be flush with the window titlebar.

**Screenshots**

See above

**Logs**

No logs to report

**Comment by GroovinChip** [comment]
@lesliearkorful What's the rationale for having this `SizedBox` at the top of the `Sidebar`?

**Comment by lesliearkorful** [comment]
It's the top padding (or safe area) for sidebars when the native title bar is hidden or transparent.
That top padding is equal to the height of the title bar in macos

You're seeing it like this because your app is showing the native macos title bar.

I guess we'll need a property to add or remove the top padding for the side bar.

I attached a screenshot of the Apple music app
![image](https://user-images.githubusercontent.com/4087388/125302483-83cffc00-e31b-11eb-8fd6-8a49f19a48ad.png)

**Comment by GroovinChip** [comment]
It happens in projects where I hide the native titlebar as well:
![Screen Shot 2021-07-12 at 10 29 10 AM](https://user-images.githubusercontent.com/4250470/125304967-00eb7900-e2fc-11eb-9697-bc76026e4623.png)
