### ISSUE TITLE
Drag scrolling is disabled after upgrading to Flutter 2.5

### ISSUE THREAD

**Issue by vumanhsn97** [macosui/macos_ui#154]
**Description**

Create new scroll behavior to migrate flutter 2.5 [https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag)

MacosApp widget does not apply new custom scroll behavior
` MacosApp(
              scrollBehavior: MyCustomScrollBehavior(),`

**Comment by GroovinChip** [comment]
@vumanhsn97 do you have a gif or something that you can provide that demonstrates the bug?

**Comment by GroovinChip** [comment]
Upon cursory inspection it appears that our `MacosScrollBehavior` is not overriding the new `dragDevices` getter. This should be trivial to update, but I would still like to see a gif of the bug before I do please.

**Comment by vumanhsn97** [comment]
When you upgrade to flutter 2.5, MacosApp can't able using mouse to scroll a listview. It is only working with scroll wheel [https://streamable.com/6prtrc](https://streamable.com/6prtrc)

Everything is working well with flutter 2.2

**Comment by GroovinChip** [comment]
Thank you for providing more detail. This does indeed seem to me to be related to overriding the new `dragDetails` getter in Flutter 2.5. However, I'm not convinced that drag scrolling should be allowed with `macos_ui`, given that it is a desktop framework. I will give it some thought.

**Comment by GroovinChip** [comment]
https://twitter.com/groovinchip/status/1437422926580572160?s=21

**Comment by GroovinChip** [comment]
@vumanhsn97 I will not be implementing drag scrolling for `macos_ui`. If you require it, please feel free to fork the package and add it via the `MacosScrollBehavior` class.
