### ISSUE TITLE
💡 Add hover effects for MacosIconButtons and MacosBackButtons 

### ISSUE THREAD

**Issue by whiplashoo** [macosui/macos_ui#168]
## Use case

Currently, when the user hovers over a `MacosIconButton` or similar, there is no visual feedback to show that the element is interactive. Previously, the cursor changed to a hand cursor, but this was changed in 0.9.2 to better match Apple guidelines.

## Proposal

Add a visual cue, like a drop shadow, to the `MacosIconButton` and `MacosBackButton`, when the user's mouse cursor hovers over them. 

This is already used in Apple UI design, for example in Notes:

https://user-images.githubusercontent.com/9117427/137474637-846f20cb-cd5b-4da0-be89-516d7c349f8c.mp4

or in Safari (with a dark theme):

https://user-images.githubusercontent.com/9117427/137474879-8c7e2eaf-2967-49af-80ee-f67123babd48.mov

**Comment by vietz-dev** [comment]
I'd like to tackle this problem :) 

However if you (@whiplashoo) are already onto this, I'd search for another issue of course.

**Comment by whiplashoo** [comment]
@kiesman99 No problem, I haven't started working on this. 

If it helps, to provide hover effects on other desktop widgets, I used something like this:

```dart
...
MouseRegion(
      onEnter: (e) {
        setState(() {
          _isHovered = true;
        });
      },
      onExit: (e) {
        setState(() {
          _isHovered = false;
        });
      },
      child: GestureDetector(
...
```

**Comment by whiplashoo** [comment]
@kiesman99 any luck? I might be close to building this on my version, so I can try to make a PR.

**Comment by vietz-dev** [comment]
Hey @whiplashoo if you already have an implementation feel free to take on. Unfortunately I've hadn't had much time in the last few weeks.
