### ISSUE TITLE
Could MacosTheme be a type of ThemeData so i could use it in my MaterialApp ?💡 

### ISSUE THREAD

**Issue by erf** [macosui/macos_ui#180]
## Use case

I'm building a macOS app using Flutter and i would like to use some the macOS theming but still use the regular classes for `MaterialApp` and `Scaffold`.

## Proposal

Could you just use the regular `ThemeData`. Why the need to create a `MacosTheme` class? 

## Rant on cross platform packages

I appreciate the effort, but it seem like these cross platform packages they have limitations. Once you buy into one, like `macos_ui` or `flutter_platform_widgets`, it seems it locks you down into that specific platform, as now you can't support other platforms without rebuilding everything (!), and there is always limitations to these packages and their widgets. I would rather see more independent packages where you can pick and choose UI elements or `ThemeData` themes which would fit with the default `MaterialApp` or `Scaffold`.

**Comment by GroovinChip** [comment]
Hi there.

Thanks for filing this issue. I understand your frustrations and agree that Flutter itself should offer theming and components that address platform specific styles for desktop. 

If you'd like to use macOS theming with the `material` library, I suggest that you lift the style values from `macos_ui` and create your own `ThemeData` for use with regular `material` widgets.
