### ISSUE TITLE
🐛 Crash in PushButton when using custom theme data

### ISSUE THREAD

**Issue by edwardaux** [macosui/macos_ui#183]
**Description**

I've been dabbling with using theming info and created a custom theme data using:
```
MacosThemeData(pushButtonTheme: const PushButtonThemeData(color: Colors.amber))
```

However, this causes a crash when I use a `PushButton` widget on this line: https://github.com/GroovinChip/macos_ui/blob/65b53fa7529d069f5227d3ae521ac7272d74ea34/lib/src/buttons/push_button.dart#L226

Now, I can see that if I provide a value for `secondaryColor` in `PushButtonThemeData` then this problem will go away. However, the fact that this field is defined as an optional in the theme data suggests that this shouldn't be the case. 

Not really sure what the "solution" is. Maybe it is to make that field mandatory, maybe just some documentation, maybe an assertion if it is null, maybe defaulting to the [default theme value](https://github.com/GroovinChip/macos_ui/blob/65b53fa7529d069f5227d3ae521ac7272d74ea34/lib/src/theme/macos_theme.dart#L217).

Anyway, just thought I'd mention it.

**Comment by whiplashoo** [comment]
Yes, this has been discussed in a [previous PR](https://github.com/GroovinChip/macos_ui/pull/182#issuecomment-1066090880). It will be fixed soon!

**Comment by edwardaux** [comment]
Ah, sorry... I didn't notice that. Thanks... if it is already being tracked, I'm happy for this issue to be closed
