### ISSUE TITLE
📖 Food for thought regarding the burred sidebar advice

### ISSUE THREAD

**Issue by edwardaux** [macosui/macos_ui#184]
Prior to this project supporting the blurred sidebar, I had already implemented it in my own macos desktop app.  Like you I started with the suggestion from [this comment](https://github.com/flutter/flutter/issues/59969#issuecomment-764955247).

However, the source code that is in that comment really isn't the right way to do it. Mucking around with `contentView` and its position in the view hierarchy is not the right way to do it. It has a bunch of knock-on effects.

I added a [comment](https://github.com/flutter/flutter/issues/59969#issuecomment-916682559) to that issue that uses a more traditional AppKit-way of doing things.

Now, I know that this project can't really do much in terms of providing Swift code... however, I do feel like it would be worth considering what advice is shared for this code. Note that I'm not saying my code is "the right way" or "the only way"... just that the current suggestion isn't really idiomatic Swift code. Just some food for thought.

**Comment by GroovinChip** [comment]
@edwardaux feel free to open a PR with this documentation update.
