### ISSUE TITLE
🐛 Remove fonts from repo and packaged assets

### ISSUE THREAD

**Issue by edwardaux** [macosui/macos_ui#187]
**Description**

I'm using macos_ui in my current app and happened to notice that one of Apple's San Francisco's fonts is distributed. I'm not a lawyer, but if you look at the license for those fonts (which is [included in the macos_ui repo](https://github.com/GroovinChip/macos_ui/blob/e0ebd3babf36d5f7382dc0a4a219cb685d6273af/fonts/SFProTTF/SFPro_Font_License.rtf#L44)), they are VERY clear about whether shipping them in an app is allowed (it isn't).

Searching through the macos_ui codebase, as best I can tell, the only place where the San Francisco fonts are referenced are:

* In the `assets` section of `pubspec.yml`
* The contents of the `fonts` directory
* In the [Typography](https://github.com/GroovinChip/macos_ui/blob/e0ebd3babf36d5f7382dc0a4a219cb685d6273af/lib/src/theme/typography.dart#L4) source

I have a theory that everything would still work if you we removed all three of the above and changed the `Typography` source to use:
```
const _kDefaultFontFamily = '.AppleSystemUIFont';
```

But I'm not really sure how to confirm this theory. Thoughts?

**Steps To Reproduce**

Build an app that embeds `macos_ui` and look at the contents of the bundle.

![image](https://user-images.githubusercontent.com/1574429/161326357-7ec5cab4-c64d-4ce0-a57f-c5a2ca0986cf.png)

**Expected behavior**

The fonts shouldn't be bundled.

**Comment by Andrewngabriel** [comment]
Just tried this locally and didn't notice any difference after switching the font with `.AppleSystemUIFont`. I'll go ahead and open a PR with this fix 👍

**Comment by GroovinChip** [comment]
> Just tried this locally and didn't notice any difference after switching the font with `.AppleSystemUIFont`. I'll go ahead and open a PR with this fix 👍

Excellent, thank you! And thank you @edwardaux for reporting this!

**Comment by GroovinChip** [comment]
@Andrewngabriel I went ahead and took care of this

**Comment by edwardaux** [comment]
@GroovinChip I just noticed that the commit you referenced above doesn't change the font name in `typography.dart`. 

One small nitpick if I may... I believe the "correct" name of the system font is `".AppleSystemUIFont"`, but the value that is specified in typography is `"SanFranciscoPro"`. This happens to "work" because flutter just falls back to the standard system font if it can't find the specified one... it would work just as well if we set the system font name to `"GroovinChip"` 😄 

Perhaps, just for correctness-sake, we could set the default font family to `".AppleSystemUIFont"`?

**Comment by GroovinChip** [comment]
> @GroovinChip I just noticed that the commit you referenced above doesn't change the font name in `typography.dart`.
> 
> One small nitpick if I may... I believe the "correct" name of the system font is `".AppleSystemUIFont"`, but the value that is specified in typography is `"SanFranciscoPro"`. This happens to "work" because flutter just falls back to the standard system font if it can't find the specified one... it would work just as well if we set the system font name to `"GroovinChip"` 😄
> 
> Perhaps, just for correctness-sake, we could set the default font family to `".AppleSystemUIFont"`?

Works for me, I'l get that fixed up in a moment. Thanks for catching that!

**Comment by GroovinChip** [comment]
Done!
