### ISSUE TITLE
🐛 Active tab icon should change to white when tab is active

### ISSUE THREAD

**Issue by Andrewngabriel** [macosui/macos_ui#190]
**Description**

At the moment if you click on any left navigation tab, the leading icon remains blue which becomes invisible against the blue foreground of the highlighted tab.

**Steps To Reproduce**

1. Run the example app
2. Click on any of the navigation tabs on the left side
3. You should see that any tab you click on becomes activated while the leading icon remains blue therefore not being visible.

**Expected behavior**

According to the design spec, the icon color should change to white when the tab is selected and active.

**Screenshots**

**Current:**

![Screen Shot 2022-04-16 at 11 44 19 PM](https://user-images.githubusercontent.com/11186948/163699411-b1759aa8-5e49-4292-8b39-d731b9eefee1.png)

**Design:**

| Dark      | Light |
| ----------- | ----------- |
| ![Screen Shot 2022-04-16 at 11 46 41 PM](https://user-images.githubusercontent.com/11186948/163699470-8d9b64fa-a91b-4760-bd02-23797876b20d.png)      | ![Screen Shot 2022-04-16 at 11 46 55 PM](https://user-images.githubusercontent.com/11186948/163699476-b86f45c0-685f-4503-afdc-face3d20669c.png)      |

**Comment by GroovinChip** [comment]
Good catch, thank you for reporting this!
