### ISSUE TITLE
Repo setup tasks

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#2]
- [x] Add info to `CONTRIBUTING.md` (branch structure, etc)
- [x] Decide on lint rules and add them to `analysis_options.yaml`
- [x] Decide on any actions and add them
- [x] Decide on a pull request template and add it
- [ ] ~~Decide on an issue template and add it~~

**Comment by GroovinChip** [comment]
Lint rules more or less addressed by #16 and #17

**Comment by GroovinChip** [comment]
Next up will be PR templates

**Comment by bdlukaa** [comment]
I'd be good to just follow dart conventions. (dartfmt)

**Comment by GroovinChip** [comment]
I'd like to have a checklist considering (at least)
* Addressed analyzer warnings as best as could be
* Dartfmt on all changed files
* Optimize imports on all changed files
* Documentation added/updated if applicable
* Version bump/changelog updated

Dartfmt/optimize imports could potentially be addressed in an Action? I'm still not great at those 😅

**Comment by GroovinChip** [comment]
Decided issue templates not necessary at this time.

Decided on https://github.com/marketplace/actions/dart-flutter-package-analyzer as an Action.
