### ISSUE TITLE
`MacosColorWell` should account for non-macOS platforms

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#218]
Currently, `MacosColorWell` does not account for the possibility that it will be used on platforms other than macOS. As such, when clicked, it should either:
* Throw an  `UnsupportedPlatformException`
* Open a non-platform dependent color picker'

I am undecided about which option is better. I welcome anyone's thoughts on the matter.

**Comment by whiplashoo** [comment]
In the particular case of the `MacosColorWell`, I believe that it should just throw an `UnsupportedPlatformException` for the time being. If there were a Flutter widget for a color picker, I would suggest using that instead, but implementing our own would be a bit too much of a task (there are a lot of packages that do just that and have their own issues and requirements).

In the general sense, I think that it makes more sense to focus solely on the macOS platform, and also make users aware of this fact. It's rare that anyone would use macos_ui for a Windows/Linux app, and testing for differences and inconsistencies while supporting all platforms, is probably not feasible. We can also point to the other platforms' UI libraries (fluent_ui and yaru) for users that may try to develop a cross-platform desktop app, just like fluent_ui's README does.
