### ISSUE TITLE
💡Some features I want from toolbar 

### ISSUE THREAD

**Issue by dbsxdbsx** [macosui/macos_ui#225]
## Use case
I need a toolbar, which lay out vertically at the right/left side of window. And  it can hide if mouse moves over or in. Also some other feature I need, which I stated below.

## Proposal for both `ToolBarIconButton` and `ToolBarPullDownButton`
1. Add property `toolTip` --- showing description when mouse hovers on icon(it is not the property `label`);
2. Add `ToolBarDivider` which draw a line to separate toolbar icons, as another divider except for `ToolBarSpacer`;
3. Add property `rotate` to make icon rotates like `RotatedBox`, currently, the `ToolBarPullDownButton` cannot be roatated by  `RotatedBox`;
4. Add property `focused`, when `focused`, there would be a box line drawn outside of the button icon, implying the status of the specific button.
5. Add property `onLongPressed`;

## workaround
Currently, for animation show/hide effect , I work around by wrapping `ToolBar` with `AnimatedContainer` and `MouseRegion`.  But it is a little hard to make content of  `ToolBar` paint correctly ---there is always a big margin on top of button icons when I used a fixed `AnimatedContainer` height.
For proposal 1 and 2, I can't work around it.
For proposal 3, to get vertical layout, I first rotated the whole `toolBar`, but then I also need to rotate each icon inside of the `toolBar`, here only  `widget` can be rotated by `RotatedBox`, so `ToolBarPullDownButton` is failed to rotate this way, since the icon type is sepcified as `iconData`.
for proposal 4, I tried to work it out with `decoration` within `container`, but seems to be no feasible as item of `ToolBar`.
for proposal 5, I am not using this feature at present, but I think it useful, referring to the feature of `commandBar` in [FluentUi](https://pub.dev/packages/fluent_ui).

**Comment by GroovinChip** [comment]
Hello @dbsxdbsx, and thanks for filing this issue.

I haven't seen anything in the Apple Human Interface Guidelines about a vertical toolbar, nor have I seen an actual macOS app with such a toolbar. Can you provide an existing example of this please?

Thanks!

**Comment by whiplashoo** [comment]
Hey @dbsxdbsx , the new `CustomToolbarItem` (added via #228) can help with some of the customizations you need.

**Comment by dbsxdbsx** [comment]
> Hello @dbsxdbsx, and thanks for filing this issue.
> 
> I haven't seen anything in the Apple Human Interface Guidelines about a vertical toolbar, nor have I seen an actual macOS app with such a toolbar. Can you provide an existing example of this please?
> 
> Thanks!

Hi, actually I have little experience with mac app, and I have no idea what mac app uses vertical layout. But indeed I want to implement this vision effect in my app.  It is somewhat like [this flutter package](https://pub.dev/packages/collapsible_sidebar).  But I do like `ToolBarPullDownButton`, so I would prefer to deal with it all in `[macos_ui](https://github.com/GroovinChip/macos_ui)`.

**Comment by dbsxdbsx** [comment]
> Hey @dbsxdbsx , the new `CustomToolbarItem` (added via #228) can help with some of the customizations you need.

Thanks, I think it useful, I would give it a try first.

**Comment by whiplashoo** [comment]
@dbsxdbsx A `tooltipMessage` property is now available, to use with toolbar items, as described in your first suggestion.

**Comment by GroovinChip** [comment]
Correction - it will be available once I release it 😅 (I’m AFK)

**Comment by whiplashoo** [comment]
Of course!
