### ISSUE TITLE
💡 Add end sidebar support

### ISSUE THREAD

**Issue by MarnoDev** [macosui/macos_ui#226]
## Use case

![image](https://user-images.githubusercontent.com/14787921/167097687-fa90059f-fa79-418e-a28e-d3f42fb7a2a7.png)

## Proposal

End sidebar like Xcode does

**Comment by GroovinChip** [comment]
Hi, @MarnoDev! Thanks for requesting this feature; I think it's reasonable. I'll put it on the backlog.
