### ISSUE TITLE
After upgrading to Flutter 3.0 I can't run applications with macos_ui

### ISSUE THREAD

**Issue by jtdLab** [macosui/macos_ui#247]
Describe the bug
After the last Flutter update I could no longer run applications with macos_ui without errors. 

To Reproduce
1. Upgrade to Flutter 3.0
2. Run a project that has macos_ui
3. The error will appear in the terminal

Flutter doctor:

[✓] Flutter (Channel stable, 3.0.0, on macOS 11.6.5 20G527 darwin-x64, locale de-DE)
    • Flutter version 3.0.0 at /usr/local/Caskroom/flutter/3.0.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/jonas/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 799F1DAE-8CDC-4540-AE90-1ED2B89FDBD7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2
      (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.6.5 20G527 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.64
    ! Error: DPhone is not connected. Xcode will continue when DPhone is connected. (code -13)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
    ! Error: timsegeco is not connected. Xcode will continue when timsegeco is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by GroovinChip** [comment]
Hello @jtdLab! Thanks for filing this issue. 

I am already hard at work migrating `macos_ui` to support Flutter 3, and I expect that I will release a new version by the end of the week that does so.
