### ISSUE TITLE
☂️ Revamp Scaffold

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#26]
Discussion here: https://github.com/GroovinChip/macos_ui/discussions/15

- [x] Support multiple resizable panels
- [x] Scaffold should show/hide any sidebars/resizable panes at a specified breakpoint
- [x] Scaffold `Titlebar` should support `Toolbar` widgets

**Comment by GroovinChip** [comment]
Another thing - Toolbar and ResizablePane dividers should respect their boundaries, as seen here:
<img width="766" alt="Screen Shot 2021-04-15 at 10 38 30 PM" src="https://user-images.githubusercontent.com/4250470/114963694-50c0be00-9e3b-11eb-9f7a-1c32a2150e08.png">
- [ ] No horizontal toolbar divider for Sidebars

**Comment by lesliearkorful** [comment]
Sidebars have a horizontal divider at the top when they're scrolled.
Even more like a shadow
![image](https://user-images.githubusercontent.com/4087388/115014344-ba73b300-9ea1-11eb-90c6-de36acfebc50.png)

**Comment by GroovinChip** [comment]
Ah, you're correct.

**Comment by GroovinChip** [comment]
@whiplashoo this will play into #80

**Comment by dbsxdbsx** [comment]
I just wonder how to add vertical divider to separate item in toolbar? Now I only found `ToolBarSpacer`.

**Comment by whiplashoo** [comment]
@dbsxdbsx that's not available yet, but definitely in the roadmap. If you want, please open a separate issue to track it.

**Comment by GroovinChip** [comment]
@dbsxdbsx Yes, please feel free to open an issue for this feature.
