### ISSUE TITLE
example app crashes on linux

### ISSUE THREAD

**Issue by sgehrman** [macosui/macos_ui#263]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
js_primitives.dart:30 The following ArgumentError was thrown building WidgetGallery(state: _WidgetGalleryState#f993c):
js_primitives.dart:30 Invalid argument(s): Platform linux has no standard menu for PlatformProvidedMenuItemType.about.
js_primitives.dart:30 Call PlatformProvidedMenuItem.hasMenu to determine this before instantiating one.
js_primitives.dart:30 
js_primitives.dart:30 The relevant error-causing widget was:
js_primitives.dart:30   WidgetGallery WidgetGallery:file:///home/steve/expr/macos_ui/example/lib/main.dart:33:23
js_primitives.dart:30 
js_primitives.dart:30 When the exception was thrown, this was the stack:
js_primitives.dart:30 dart:sdk_internal 5080:11                                 throw_
js_primitives.dart:30 packages/flutter/src/widgets/title.dart.lib.js 30836:21   <fn>
js_primitives.dart:30 packages/flutter/src/widgets/title.dart.lib.js 30839:26   toChannelRepresentation
js_primitives.dart:30 packages/flutter/src/widgets/title.dart.lib.js 30631:38   serialize
js_primitives.dart:30

**Comment by GroovinChip** [comment]
This is not a bug - the usage of PlatformMenuBar in the example only supports macOS.

**Comment by sgehrman** [comment]
Yeah, it runs if I delete the PlatformProvidedMenuItem.

You should at least make the example work on linux and not crash.  I'm writing a desktop app crossplatform.  If I were writing macos only, I would just use swift.
