### ISSUE TITLE
SidebarItem with disclosureItems and leading widget places disclosure turn-down widget after leading widget 

### ISSUE THREAD

**Issue by slewallen** [macosui/macos_ui#268]
**Description**

On Mac OS, an outline view item with disclosure items places the disclosure turn-down before any icon for the outline view item.  However, macos_ui is placing the leading icon before the turn-down icon.  

See attached screenshot comparing what macos_ui is doing in comparison to actual Mac OS.

**Steps To Reproduce**

Modify the example at "https://pub.dev/packages/macos_ui/example" to include a leading widget for the Disclosure SidebarItem as such:

                SidebarItem(
                  label: Text('Disclosure'),
                  leading: MacosIcon(CupertinoIcons.alarm),
                  disclosureItems: [
                    SidebarItem(
                      leading: MacosIcon(CupertinoIcons.infinite),
                      label: Text('Colors'),
                    ),
                    SidebarItem(
                      leading: MacosIcon(CupertinoIcons.infinite),
                      label: Text('Item 3'),
                    ),
                  ],
                ),

Notice that the order is incorrect.  For a correct example, see Mac OS Finder or Mac OS Mail.

</details>

**Expected behavior**

Order of disclosure turn-down and leading widget should be reversed.  When a SidebarItem has disclosure items and a leading widget along with a label, it should be displayed as: "> 😀 Label" instead of "😀 > Label" in sidebar item.

**Screenshots**

<img width="598" alt="Comparision of macos_ui and actual Mac OS" src="https://user-images.githubusercontent.com/23299259/175834584-bbc2f370-f327-4080-b69d-218e37e33682.png">

**Comment by GroovinChip** [comment]
@whiplashoo what do you think about this? It looks like the current implementation is indeed incorrect, but I need to verify.

**Comment by whiplashoo** [comment]
Yes, indeed, I also see it in Finder or Disk Utility:

<img width="629" alt="Screenshot 2022-06-30 at 11 40 49 PM" src="https://user-images.githubusercontent.com/9117427/176774558-01e7ad2f-74b6-4139-a49c-7ee04fa544ca.png">

**Comment by GroovinChip** [comment]
Alrighty then, I'll whip up a fix. Thanks for reporting this @slewallen
