### ISSUE TITLE
Let MacosTabView be splitable and dragable like a dock

### ISSUE THREAD

**Issue by dbsxdbsx** [macosui/macos_ui#294]
## Use case
I am building a desktop app. Since there are many sub layouts(I mean MacosTabView here), I hope users could customize the layout by themselves. Something like this:https://pub.dev/packages/docking 
## Proposal
For example, If there are 2 MacosTabViews, with each has 2 tabs. I hope each tab could be dragged out to dock to a new place or dock to another MacosTabViews.  If possible, I also hope the MacosTabViews could be dragged to customize their positions.

**Comment by GroovinChip** [comment]
Hi @dbsxdbsx, thanks for filing this feature request! I'm not aware of anything in the Apple Human Interface Guidelines that outlines this behavior and I'm pretty sure I've not seen it in any mac applications. Do you have an example of an app that was built according to the Human Interface Guidelines that has this behavior, or can you point me towards some documentation that describes this?

**Comment by dbsxdbsx** [comment]
> Hi @dbsxdbsx, thanks for filing this feature request! I'm not aware of anything in the Apple Human Interface Guidelines that outlines this behavior and I'm pretty sure I've not seen it in any mac applications. Do you have an example of an app that was built according to the Human Interface Guidelines that has this behavior, or can you point me towards some documentation that describes this?

I guess  Visual Studio could be the example---the sub windows in it are quite flexible and users can save their own layout.

**Comment by GroovinChip** [comment]
Right, but that's not an Apple design thing. This package is for implementing Apple's macOS design language. Here's the page for TabVIew - https://developer.apple.com/design/human-interface-guidelines/components/layout-and-organization/tab-views

**Comment by dbsxdbsx** [comment]
> Right, but that's not an Apple design thing. This package is for implementing Apple's macOS design language. Here's the page for TabVIew - https://developer.apple.com/design/human-interface-guidelines/components/layout-and-organization/tab-views

That's ok. So I should implement this effect by myself or other packages.
