### ISSUE TITLE
How to use pop up selections without a `MacosTheme` parent widget?

### ISSUE THREAD

**Issue by lucasjinreal** [macosui/macos_ui#304]
Hi, macOS_ui looks nice. How can I using this pop up selection without using any macostheme parent?

<img width="174" alt="image" src="https://user-images.githubusercontent.com/21303438/190849407-2682c96f-5d57-40dc-a0ec-8054832a999d.png">

I just want call this popup and popup this window:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/21303438/190849431-0b1f285d-0efa-4ddc-b3e5-52e2579503d5.png">

is that doable?

**Comment by GroovinChip** [comment]
Hi @jinfagang. I'm not sure why you'd want to use this widget without a `MacosTheme`parent widget. Widgets in this library depend on it for what I hope are obvious reasons.

**Comment by lucasjinreal** [comment]
@GroovinChip Hi, part of my project is highly couple with customized skeleton, it's very hard to wrap another layer on top of it. As for I just wanna this window, so really hoping to use it as a simple widget, rather than stack all dependencies UI tree on it.

**Comment by GroovinChip** [comment]
> @GroovinChip Hi, part of my project is highly couple with customized skeleton, it's very hard to wrap another layer on top of it. As for I just wanna this window, so really hoping to use it as a simple widget, rather than stack all dependencies UI tree on it.

You might be better off simply making your own dialog, then. Since this library is open-source, it shouldn't be too difficult.

**Comment by lucasjinreal** [comment]
@GroovinChip  Hi, which widget should I using on macOS to have above effect? I cannot found a widget which pretty close to this

**Comment by GroovinChip** [comment]
> @GroovinChip  Hi, which widget should I using on macOS to have above effect? I cannot found a widget which pretty close to this

`MacosDialog`

**Comment by lucasjinreal** [comment]
@GroovinChip thanks, Does `macosDialog` have the blur effect?

**Comment by GroovinChip** [comment]
> @GroovinChip thanks, Does `macosDialog` have the blur effect?

It does not.

**Comment by lucasjinreal** [comment]
okay. then it's not my want
