### ISSUE TITLE
add `initialDate` to `MacosDatePicker`

### ISSUE THREAD

**Issue by Luckey-Elijah** [macosui/macos_ui#310]
## Use case
I'd like to control the initial date set in `MacosDatePicker` widget.

## Proposal

Create a parameter `initialDate` that sets `_MacosDatePickerState._initialDate` on init state. If the value of the parameter `initialDate` is `null`, then use `DateTime.now()`.

Example of ideal usage:

```dart
MacosDatePicker(
  style: DatePickerStyle.textual,
  initialDate: DateTime(2022, 10, 10),
  onDateChanged: _onDateChanged,
)
```

**Comment by Luckey-Elijah** [comment]
Feel free to assign to me for a contribution :smile:

**Comment by GroovinChip** [comment]
I think this is a reasonable request. @Luckey-Elijah Are you still interested in contributing?

**Comment by Luckey-Elijah** [comment]
Yes, I can work on this!
