### ISSUE TITLE
Sidebar with bottom 

### ISSUE THREAD

**Issue by anilcngz** [macosui/macos_ui#311]
## Use case

There is no way to unselect a SideBarItem because we need to provide a currentIndex (It must be in the range of 0 to [items.length]). I think because of that when I add a Settings page by using bottom property as below and click on it, still SideBarItem is shown as selected.

```
MacosWindow(
    sidebar: Sidebar(
      top: const Text('LOGO'),
      minWidth: 200,
      builder: (context, _) => SidebarItems(
        currentIndex: _currentIndex,
        items: items,
        itemSize: SidebarItemSize.large,
        onChanged: (index) => _onItemTapped(context, index),
      ),
      bottom: MacosListTile(
        leading: const MacosIcon(CupertinoIcons.profile_circled),
        title: const Text('Settings'),
        subtitle: Text(userEmail ?? ''),
        onClick: () => context.go('/settings'),
      ),
    ),
    child: widget.child,
  )
```

## Proposal

<img width="1112" alt="Screen Shot 2022-10-15 at 13 19 12" src="https://user-images.githubusercontent.com/24778105/195981201-5e8e23b5-bf54-47a7-8894-c449bfa13112.png">

**Comment by Yetispapa** [comment]
@anilcngz, did you manage to find a solution?

**Comment by GroovinChip** [comment]
@anilcngz This is expected behavior IMO. I think if you want to display a settings page when the `bottom` is clicked you should push a new route, one that doesn't contain a sidebar.

**Comment by anilcngz** [comment]
@GroovinChip Attached you can find the App Store app screenshot, it has a very similar design. When I click the bottom item, it behaves like side bar item.

![Screenshot 2023-01-16 at 10 34 20](https://user-images.githubusercontent.com/24778105/212622459-34b5bc73-5cad-481d-b56f-4db05e62e2ce.png)

**Comment by GroovinChip** [comment]
> @GroovinChip Attached you can find the App Store app screenshot, it has a very similar design. When I click the bottom item, it behaves like side bar item.
> 
> 
> 
> ![Screenshot 2023-01-16 at 10 34 20](https://user-images.githubusercontent.com/24778105/212622459-34b5bc73-5cad-481d-b56f-4db05e62e2ce.png)
> 
> 

Apple unfortunately do not consistently follow their own guidelines across their app. Do you know of any other Apple (or other) apps that have this behavior on macOS?

**Comment by anilcngz** [comment]
I was using rize.io for a while, it also has a similar experience. But I couldn't find any other Apple (or other) apps with a bottom Menu Item. 

If it's like this in the Apple guideline as you said, we can close this issue.

<img width="684" alt="Screenshot 2023-01-22 at 22 48 44" src="https://user-images.githubusercontent.com/24778105/213937061-9e8b6c77-0928-46e6-9ed0-9032ca79c158.png">

**Comment by GroovinChip** [comment]
> I was using rize.io for a while, it also has a similar experience. But I couldn't find any other Apple (or other) apps with a bottom Menu Item.
> 
> If it's like this in the Apple guideline as you said, we can close this issue.
> 
> <img alt="Screenshot 2023-01-22 at 22 48 44" width="684" src="https://user-images.githubusercontent.com/24778105/213937061-9e8b6c77-0928-46e6-9ed0-9032ca79c158.png">

That looks like a custom sidebar, not an [Apple-guidelines](https://developer.apple.com/design/human-interface-guidelines/components/navigation-and-search/sidebars#) sidebar. In fact, the guidelines don't appear to mention this paradigm at all. So IMO the `bottom` should not be used to perform navigation to a view that a `SidebarItem` is connected to.
