### ISSUE TITLE
No wallpaper tint support

### ISSUE THREAD

**Issue by bernaferrari** [macosui/macos_ui#315]
I wish there were support for Monterey background colors:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/351125/200044831-ef91beb1-1e17-45f4-b4c7-e8445b99b93a.png">

<img width="657" alt="image" src="https://user-images.githubusercontent.com/351125/200044775-3e16b8f4-765f-41c6-a8b2-2a76e60f7815.png">

**Comment by Adrian-Samoticha** [comment]
Hello,

I am the maintainer of the macOS support of the [flutter_acrylic](https://github.com/alexmercerind/flutter_acrylic) package, which has recently received wallpaper tinting support.

I have not tried it, yet, but there _might_ be a way to make both packages work together to achieve the desired effect, at least until wallpaper tinting is officially supported by macos_ui.

**Comment by Adrian-Samoticha** [comment]
Just in case anyone is interested, I managed to implement this feature into macos_ui and started a discussion regarding its implementation: #322
