### ISSUE TITLE
Can't run the main demo

### ISSUE THREAD

**Issue by kirill-grouchnikov** [macosui/macos_ui#324]
The latest clone of the project. Run `flutter run` from the `example` folder and choose to run on macOS (my version is 13.0.1):

```
lib/main.dart:110:7: Error: No named parameter with the name 'child'.
      child: MacosWindow(
      ^^^^^
../../../flutter/packages/flutter/lib/src/widgets/platform_menu_bar.dart:462:9: Context: Found this candidate, but the arguments don't match.
  const PlatformMenuBar({
        ^^^^^^^^^^^^^^^
```

**Comment by kirill-grouchnikov** [comment]
Opening `example/lib/main.dart` in IntelliJ shows this:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/52874/206004310-673e7831-d287-41b8-ba55-21a7a33d6f76.png">

**Comment by kirill-grouchnikov** [comment]
Replacing `child` with `body` in line 110 fixes the issue and makes the app run successfully

**Comment by GroovinChip** [comment]
@kirill-grouchnikov I believe you encountered this issue because you were using an older version of Flutter on the `stable` channel at the time. `PlatformMenuBar` changed `body` to `child` in the latest version by that time.
