### ISSUE TITLE
Override method error - _TextFieldSelectionGestureDetectorBuilder onSingleTapUp

### ISSUE THREAD

**Issue by PierreBresson** [macosui/macos_ui#335]
Hi,

I can't build my project, I get the following error : 

```
Error (Xcode):
../../../.pub-cache/hosted/pub.dev/macos_ui-1.7.6/lib/src/fields/text_field.dart
:108:35: Error: The parameter 'details' of the method
'_TextFieldSelectionGestureDetectorBuilder.onSingleTapUp' has type
'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails',
in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.
```

I tried flutter clean and flutter pub cache repair  but still get the error.

Here is the output of flutter doctor : 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.7.0-29.0.pre.1, on macOS 13.1 22C65 darwin-x64,
    locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

And in my pubspec : 

```
environment:
  sdk: ">=3.0.0-171.0.dev <4.0.0"
```

**Comment by GroovinChip** [comment]
This might be because you are on the master channel, and this project is based on the stable channel. Try moving to stable and see if that helps.

**Comment by PierreBresson** [comment]
Fixed the issue, thanks :)

**Comment by Amoour** [comment]
How do you fix it? Can you tell me about it? thank you

**Comment by asadamatic** [comment]
I did not use the `macos_ui` package, but I was using `flutter_neat_and_clean_calendar` which depended on the `macos_ui` package. Updating `flutter_neat_and_clean_calendar` to the latest version fixed it.

Here's the list of packages that depend on `macos_ui`, you can verify if you're using any of these packages.
