### ISSUE TITLE
Bottom Resizable Pane

### ISSUE THREAD

**Issue by stMerlHin** [macosui/macos_ui#344]
## Use case

I am building a doc sharing app, from the sharing setup page, I would like to allow user to check multiple files on the bottom of the page. I thought it would be nice to make the area resizable to not hide the main content  (The selected doc) preview.
## Proposal
I don't know if there is a bottom resizable pane on the native macos ui guide but I just copy and make a few changes to the original ResizablePane widget provided in this package and I got  the result below.

[Capture vidéo du 2023-02-06 00-05-36.webm](https://user-images.githubusercontent.com/77164238/216858909-7ca5a585-4f52-43dd-ad31-8b2319107ca0.webm)

**Comment by GroovinChip** [comment]
Hi @stMerlHin. 

Your video isn't playing for me. Can you re-upload please?

Also, are you saying you've already built this? I'm unsure from your comments so I'm asking for clarity.

**Comment by stMerlHin** [comment]
Hi @GroovinChip.

I re-uploaded the video. If you still cannot play it, I'll try to record my screen with my phone, the quality will not be great but you will be able to play it.

Yes, I've already done something based on the existing ResizablePane widget. It's not ready for production but I think I can continue if the request is granted.

**Comment by GroovinChip** [comment]
No, I'm still unable to play it.

I've seen a bottom resizable pane in Xcode, I believe. I see no reason why we shouldn't have one. Go ahead and continue with your work and I'll be happy to review a PR. Thanks!

**Comment by stMerlHin** [comment]
I'm using firefox as browser, also I've played the video in chrome on my computer and the phone. Maybe using another browser should solve the problem.

Nice, I'll make a pull request very soon. Thank you for this amazing package.
