### ISSUE TITLE
macos_ui: ^1.9.1 macos_ui cannot run properly

### ISSUE THREAD

**Issue by qzgang** [macosui/macos_ui#345]
**Logs**
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/13726548/217146860-52f3a952-c17a-4c89-bea6-d796f17f8a7b.png">

**Comment by GroovinChip** [comment]
@qzgang I need some more context here. What have you done to try and resolve this? have you run `flutter clean` on your app? Are you on the latest Flutter stable channel?

**Comment by GroovinChip** [comment]
Closing due to lack of response.

**Comment by qzgang** [comment]
thanks your reply,l just saw,i have resolved it, because my flutter channel is beta . then i have already changed flutter channel then it work ok
