### ISSUE TITLE
MacosSearchField does not execute the onResultSelected function

### ISSUE THREAD

**Issue by FelixMethe** [macosui/macos_ui#348]
**Description**
When an item from the MacosSearchField is selected, the `onResultSelected` function of the field itself and the `onSelected` function of the selected `SearchResultItem` is not called.

**Steps To Reproduce**
1. Go to the Fields page of the example project
2. Type something in one of the search fields
3. Select one of the options
4. This should print the selected SearchResultItem to the console. This does not happen.

After testing, I found out that removing the lines 245 and 246 of the `search_field.dart` file resolves the error:

```dart
} else {
   _overlayEntry.remove();
```

But I am not sure if this breaks some other intended behavior.

**Comment by FelixMethe** [comment]
I tested the problem a bit more, my solution above did not work as I thought.

My new solution is to wrap the overlay with a `TextFieldTapRegion`, this keeps the TextField in focus when a button in the overlay is pressed.

If you want, I can create a pull request that solves the Issue.

**Comment by GroovinChip** [comment]
Hi @FelixMethe, thanks for reporting this bug. I've verified it. A PR fixing it would be most welcome, thanks!
