### ISSUE TITLE
Hi! Do we have any ways to use/add some validator to a MacosTextField? 

### ISSUE THREAD

**Issue by savdev-ua** [macosui/macos_ui#354]
Can't really find any possible ways to runtime validate fields and change the UI.

**Comment by GroovinChip** [comment]
Hi @savdev-ua. I'm not really sure what you're asking for. Do you mean like a `FormField`?

**Comment by savdev-ua** [comment]
@GroovinChip 
I mean MacosTextField does not have feature to add validator, just as regular TextFormField 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/62287261/219024830-7576cedc-f243-45fd-9c63-ac94b57d1b49.png">

**Comment by GroovinChip** [comment]
Could you not simply wrap the `MacosTextField` in a [`FormField`](https://api.flutter.dev/flutter/widgets/FormField-class.html) widget?

**Comment by GroovinChip** [comment]
Closing due to lack of response
