### ISSUE TITLE
DatePicker localisation/format

### ISSUE THREAD

**Issue by rklos** [macosui/macos_ui#369]
## Use case
My app uses the Polish language. In our language we have different rules for displaying date and time:
- we use `day.month.year` or, more rarely, `year-month-day` date format,
- we use leading zeros in out date format,
- we use the 24-hour format (without the AM/PM suffix),
- our week starts on Monday, not Sunday.

It would be nice to be able to customise these things in the DatePicker and TimePicker.

In the graphical version of the DatePicker, I would also like to be able to change the English month and weekday abbreviations to Polish.

## Proposal
I would like to achieve something like this using additional API params in DatePicker and TimePicker:
![CleanShot 2023-02-21 at 20 44 36](https://user-images.githubusercontent.com/34719093/220443554-9562e101-c957-4c48-9a6f-ebef45e0a00f.png)

**Comment by GroovinChip** [comment]
@rklos let's open a separate issue for time picker localization.

**Comment by rklos** [comment]
Case of the TimePicker moved to https://github.com/macosui/macos_ui/issues/442
