### ISSUE TITLE
`ToolBar.title` widget doesn't avoid the window controls when hiding the native titlebar 

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#371]
**Description**

In an app that: 

A) hides the native titlebar 
B) does not use a sidebar

the `ToolBar.title` widget collides with the window controls, like so:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/4250470/220796635-1e0b6398-ce04-4bd5-a07e-1d5f31442341.png">

**Code sample**
```dart
MacosWindow(
  child: MacosScaffold(
    toolBar: const ToolBar(
      title: Text('App'),
    ),
    children: [
      ContentArea(
        builder: (context, _) {
          return const SizedBox.shrink();
        },
      ),
    ],
  ),
),
```

**Comment by mukhtharcm** [comment]
I'm running into this same issue!
Is there any temporary fix or something?
btw, Thank you for creating this *Amazing* Library!

**Comment by GroovinChip** [comment]
> I'm running into this same issue!
> 
> Is there any temporary fix or something?
> 
> btw, Thank you for creating this *Amazing* Library!

There's no fix at this time, but this is on my to-do list to address. Please do feel free to experiment with the source code to try and fix it yourself if you need this fixed ASAP. I'd gratefully accept a PR in such a case.

And you're quite welcome! I'm very glad that I can can fill this need for people 😊

**Comment by GroovinChip** [comment]
@Adrian-Samoticha I'm thinking if we can propagate `MacosWindowUtilsConfig` throughout the widget tree, `MacosScaffold` will be able to avoid this collision. What is the best way to do that? I thought of writing a `.of(context)` method for this, but that won't work because we do not propagate the user's config internally, it's handled in their application code. We could technically have them pass it through to `MacosApp` and use an `InheritedWidget` to propagate it, but that's more work for the user. I don't really see another way, though, because that config is how they set up their app, and if we need to access that config, there's not really another way to get at it :/

**Comment by GroovinChip** [comment]
Actually, I got it! It was nowhere near as complicated as I was thinking 😂 all I had to do was this:
<img width="1992" alt="image" src="https://github.com/macosui/macos_ui/assets/4250470/753508c0-503d-4900-ab1c-c3a2d6c90424">

**Comment by whiplashoo** [comment]
Looks good with/without sidebar:

<img width="396" alt="Screenshot 2023-07-05 at 11 58 03 AM" src="https://github.com/macosui/macos_ui/assets/9117427/08979243-b1a5-44f1-b9e5-95325e2290de">
<img width="396" alt="Screenshot 2023-07-05 at 11 57 37 AM" src="https://github.com/macosui/macos_ui/assets/9117427/f0934aa1-fd8d-4ead-bcc3-c764b0f7a2a5">

**Comment by GroovinChip** [comment]
@whiplashoo I'm not seeing a title widget in your second screenshot, are you sure it works?

**Comment by whiplashoo** [comment]
@GroovinChip Yes, here it is with a simple `Text` widget for `title`:

<img width="396" alt="Screenshot 2023-07-05 at 7 40 51 PM" src="https://github.com/macosui/macos_ui/assets/9117427/b3dc04c1-2534-40cb-9d12-3db0c2397246">


<img width="396" alt="Screenshot 2023-07-05 at 7 40 24 PM" src="https://github.com/macosui/macos_ui/assets/9117427/36160844-4e4e-47d5-b29b-c2e34854d0a5">

**Comment by GroovinChip** [comment]
Thank you!
