### ISSUE TITLE
PopupButtonMenuItem has transparent background

### ISSUE THREAD

**Issue by MuhammedKpln** [macosui/macos_ui#380]
**Description**

PopupButtonMenuItem has transparent background.I've placed inside Sidebar bottom property.

https://user-images.githubusercontent.com/17166855/222497151-1e29d4e7-c03d-4872-90cd-889f8fa6d008.mp4

**Expected behavior**
It should have white or dark background, without any transparency

**Comment by GroovinChip** [comment]
Hi @MuhammedKpln. Popup menu items have a transparency effect by default. Are you expecting not to have this effect because your app does not use the native window transparency effect?

**Comment by MuhammedKpln** [comment]
I've tested on example application now, the problem only occurs when Popupbutton is used inside Sidebar widget. I'm not really sure if it is normal behaviour.


https://user-images.githubusercontent.com/17166855/222768242-21b83844-d1dc-4fd3-a552-feff2a7aca9a.mov

**Comment by GroovinChip** [comment]
I can't think of a reason offhand why this would occur. Can you please provide information on which versions of macos_ui and Flutter you're using, along with which Flutter branch?

**Comment by MuhammedKpln** [comment]
```
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (4 weeks ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1
```


`macos_ui: ^1.10.0`

**Comment by GroovinChip** [comment]
@MuhammedKpln Out of curiosity, does this still happen on the latest 2.0 beta?

**Comment by MuhammedKpln** [comment]
It is better, it does not overlap popup button.
