### ISSUE TITLE
RatingIndicator's onChanged callback is call with double value.

### ISSUE THREAD

**Issue by stMerlHin** [macosui/macos_ui#384]
## Use case
RatingIndicator takes double as value and his onChanged callback is called with double but there is no capability to half rating.

## Proposal
Make RatingIndicator's onChanged callback and value take int if there is no plan to make RatingIndicator stars to be half rated or keep using double if there is one and add capability of half rating.

**Comment by GroovinChip** [comment]
Please see the following in the readme regarding partial values:
![image](https://user-images.githubusercontent.com/4250470/223857602-a5a50cd7-26d3-415b-b4ac-b503fcf4fa9c.jpeg)

As to why we're using `double` rather than `int`...that is a great question. I'll have to look into it.

**Comment by stMerlHin** [comment]
I see, thanks for the answer. Going to close this issue.
