### ISSUE TITLE
endSidebar renders weird fragments when containing interactive elements

### ISSUE THREAD

**Issue by sebroehl** [macosui/macos_ui#385]
**Description**

Hey everyone, I noticed a strange behaviour when using the endSidebar:

When I put controls (or more spacious widgets in general) into the endSidebar, I get some really weird fragments on the left border (see screenshot), regardless whether I'm currently resizing or not. 
Do you have an idea what I'm doing wrong? Hope you can help me figure this out, because I really wanna use macos_ui for this app! 

**Steps To Reproduce**

1. Use version `1.12.2` of `macos_ui`
2. Start the provided example (and don't resize the window)
3. Use the 'Toggle End Sidebar' buttons a few times (~5 times does the trick for me). Every time the sidebar is open, click the blue PushButton a few times.
4. See that the left border of the sidebar renders with weird fragments

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:macos_ui/macos_ui.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MacosApp(
      title: 'Sidebar Test',
      theme: MacosThemeData.light(),
      darkTheme: MacosThemeData.dark(),
      themeMode: ThemeMode.dark,
      debugShowCheckedModeBanner: false,
      home: MacosWindow(
        endSidebar: Sidebar(
          shownByDefault: true,
          builder: (context, scrollController) => Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const Text('Thats a long text which makes the endSidebar produce weird fragments when clicking or resizing'),
              PushButton(
                buttonSize: ButtonSize.large,
                onPressed: () {},
                child: const Text('Button'),
              ),
            ],
          ),
          minWidth: 250,
        ),
        child: ContentArea(
          builder: (context, scrollController) {
            return MacosScaffold(
              toolBar: ToolBar(
                actions: [
                  ToolBarIconButton(
                    label: 'Toggle End Sidebar',
                    tooltipMessage: 'Toggle End Sidebar',
                    icon: const MacosIcon(
                      CupertinoIcons.sidebar_right,
                    ),
                    onPressed: () => MacosWindowScope.of(context).toggleEndSidebar(),
                    showLabel: false,
                  ),
                ],
              ),
              children: const [],
            );
          },
        ),
      ),
    );
  }
}
```

</details>

**Expected behavior**

I wouldn't expect the left border of the Sidebar to contain this fragments.

**Screenshots**

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/26088587/225648572-9fa5ba08-b486-4396-921a-0707e1f46f73.png">

**Logs**

<details>
  <summary>Logs</summary>

flutter doctor -v Output:

```
[✓] Flutter (Channel stable, 3.7.6, on macOS 12.6.1 21G215 darwin-x64, locale en-GB)
    • Flutter version 3.7.6 on channel stable at /Users/sebastianrohl/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (2 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sebastianrohl/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 12.6.1 21G215 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by GroovinChip** [comment]
Hi Sebastian! Thanks so much for filing this issue. Before I attempt to reproduce, I have two questions:
~~1. What version of Flutter are you on, and on which channel?~~ Just realized your logs provide this!
2. Which version of `macos_ui` are you using?

**Comment by sebroehl** [comment]
I use version `1.12.2`

**Comment by GroovinChip** [comment]
Excellent. Thank you!

**Comment by GroovinChip** [comment]
Oh also, last thing - did you generate your project using the [macosui_starter](https://brickhub.dev/bricks/macosui_starter/) brick? Or though normal means (flutter create, IDE wizard)?

**Comment by sebroehl** [comment]
I used the `flutter create` command 👍

**Comment by GroovinChip** [comment]
OK @sebroehl I followed your reproduction steps. Unfortunately, I was unable to reproduce the issue. Is there any more context you can share that might be able to help me reproduce?

**Comment by sebroehl** [comment]
Hmn, that's super weird. Maybe it has something to do with my system? 🙁

I recorded a small video of me reproducing the bug with the provided code example, in case I described the reproduction steps poorly.

https://user-images.githubusercontent.com/26088587/225675727-1b1276aa-b1e6-423e-9132-2ca891ffdb44.mov

**Comment by GroovinChip** [comment]
Here's what I just did:

https://user-images.githubusercontent.com/4250470/225678365-cb6dd829-4460-48ff-a2dc-aa7c5cdc8432.mov


Maybe it's a bug with macOS 12? I'm running macOS 13. Although idk why that would be, it's just a difference I noted in your logs and my setup.

**Comment by sebroehl** [comment]
Ah, okay, that could be it. I'll try to upgrade later and report back 👍🤔

**Comment by GroovinChip** [comment]
> Ah, okay, that could be it. I'll try to upgrade later and report back 👍🤔

Lol don't rush to upgrade your system on a whim, I don't know if that's the issue or not.

**Comment by sebroehl** [comment]
Wanted to upgrade anyway... But I can wait if you have other ideas that I should try. 
Another thing: Is there a way to verify that we run the application with the same dimensions (width and height of the window)?

**Comment by GroovinChip** [comment]
Oh, well if you wanted to upgrade anyway then go ahead.

Yeah, wrap your whole tree in a LayoutBuilder and print the constraints maxHeight and maxWidth

**Comment by sebroehl** [comment]
It's runs in 800 x 600 for me. But I just realized: Thought that it worked in other sizes on my end, but it actually doesn't matter whether I resize it or not. Sorry 🙁

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:macos_ui/macos_ui.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        print('Width: ${constraints.maxWidth}');
        print('Height: ${constraints.maxHeight}');
        return MacosApp(
          title: 'Sidebar Test',
          theme: MacosThemeData.light(),
          darkTheme: MacosThemeData.dark(),
          themeMode: ThemeMode.dark,
          debugShowCheckedModeBanner: false,
          home: MacosWindow(
            endSidebar: Sidebar(
              shownByDefault: true,
              builder: (context, scrollController) => Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  const Text('Thats a long text which makes the endSidebar produce weird fragments when clicking or resizing'),
                  PushButton(
                    buttonSize: ButtonSize.large,
                    onPressed: () {},
                    child: const Text('Button'),
                  ),
                ],
              ),
              minWidth: 250,
            ),
            child: ContentArea(
              builder: (context, scrollController) {
                return MacosScaffold(
                  toolBar: ToolBar(
                    actions: [
                      ToolBarIconButton(
                        label: 'Toggle End Sidebar',
                        tooltipMessage: 'Toggle End Sidebar',
                        icon: const MacosIcon(
                          CupertinoIcons.sidebar_right,
                        ),
                        onPressed: () => MacosWindowScope.of(context).toggleEndSidebar(),
                        showLabel: false,
                      ),
                    ],
                  ),
                  children: const [],
                );
              },
            ),
          ),
        );
      },
    );
  }
}
```
</details>

**Comment by GroovinChip** [comment]
Unfortunately, I still cannot reproduce the issue. I tried it at the default window size and at 800 x 600 :/

**Comment by sebroehl** [comment]
Okay, super weird. Thanks for your efforts to reproduce it. I would say we close this issue and I reopen it in case I find out something new?

**Comment by GroovinChip** [comment]
That would be prudent, yeah. I'm sorry I couldn't be of more help. Please do let me know if you have any more information in the future, and we can reopen this.
