### ISSUE TITLE
`MacosThemeData` is not very extensible

### ISSUE THREAD

**Issue by jtdLab** [macosui/macos_ui#389]
`macos_ui`s `MacosThemeData` feels not very extensible compared to `material`s `ThemeData`.

Theming using `material`:

```dart
Theme(
  data: ThemeData(
    // material component themes go here 
    extensions: // custom extensions go here
  ),
  child: MyWidget(),
);

class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) {
    // use Theme.of(context) to get material component themes or custom extensions
  }
}
```

Theming using `macos_ui`:

```dart
MacosTheme(
  data: MacosThemeData(
    // macos component themes go here 
  ),
  child: Theme(
    data: ThemeData(
      extensions: // custom extensions go here
    ),
    child: MyWidget(),
  ),
);

class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) {
    // use MacosTheme.of(context) to get macos component themes
    // use Theme.of(context) to get custom extensions
  }
}
```

Wouldn't it be more consistent if it would be possible to write:

```dart
MacosTheme(
  data: MacosThemeData(
    // macos component themes go here 
    extensions: // custom extensions go here
  ),
  child: MyWidget(),
);

class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) {
    // use MacosTheme.of(context) to get macos component themes or custom extensions
  }
}
```

Discussion welcome !

**Comment by GroovinChip** [comment]
Hi @jtdLab. Please clarify - are you requesting support for theme extensions in `MacosThemeData`?

**Comment by jtdLab** [comment]
@GroovinChip Yep. Even though this would make `macos_ui` use a `material` mechanism which might not be desired. I think logically `ThemeExtensions` should be moved to a more general lib than `material` anyway. (maybe `widgets`) Because all ui libs like `cupertino`, `macos_ui`, `fluent_ui` etc. could make use of the mechanism of registering extensions to allow consistent use of their respective theme. (But that would need some work on the flutter side).

ASFAIK `fluent_ui` allows registering `ThemeExtensions` in its `FluentThemeData` (but that might be because its based on `material`)

**Comment by GroovinChip** [comment]
> Even though this would make macos_ui use a material mechanism which might not be desired.

This is correct. `macos_ui` attempts to be as material-free as possible.

Can you provide an example where you feel `macos_ui` could benefit from theme extensions? If the need is compelling enough, I could consider creating an alternative.

**Comment by jtdLab** [comment]
@GroovinChip When implementing a design system on top of `macos_ui` using `ThemeExtension`s via ([theme_tailor](https://pub.dev/packages/theme_tailor)) it would be cool to just register the `ThemeExtension`s and us them via `MacosTheme.of(context)`.

**Comment by GroovinChip** [comment]
I don't really see the cost vs. benefit of supporting theme extensions as worth it, to be honest. I'm sorry, but this not something I'm going to support at this time.

**Comment by jtdLab** [comment]
@GroovinChip  What needs to happen to add it ?
Would you reconsider if theme extensions would be independent from `material` e.g. part of `widgets` lib ?

**Comment by GroovinChip** [comment]
@jtdLab What I would need to consider it is a lot of people needing it besides you. This is mostly a one-man show here so if there's a feature request that isn't related to the core mission of this package, it needs to be something that would be used by serious developers, putting out production apps. Otherwise the effort to implement and maintain this is not worth my time.

**Comment by damywise** [comment]
(Just curious, ignore if you find this question meaningless)
What I find most useful from FluentUI's FluentTheme.of(context) is that it provides different animation durations, a curve, and typography that (hopefully) adheres to Fluent Design system.

1. What would this `ThemeData` provide if it was to be implemented?
2. Is it possible for the answer to the previous question to be implemented without the `ThemeData`?

**Comment by GroovinChip** [comment]
> 1. What would this `ThemeData` provide if it was to be implemented?

It is only possible for me to answer this question if you can tell me what you feel is missing in terms of animation details, and typography from `macos_ui`. I am aware that many animations are slightly incorrect, which is something that I intend to deal with already. 

As for adding these things to `MacosThemeData`, I don't think that it is an appropriate place for such configuration options. I think better places for such things are on the widgets themselves and the theme data classes that customize those widgets. However, given that this is a library that aims to replicate native macOS functionality, I am reluctant to provide alternative behavior options for widgets. I do understand the argument in favor of providing such behaviors as alternatives to default behaviors, like we do with widget customizations already, this is a step further, and I'm not totally comfortable with the idea.

**Comment by sergiyvergun** [comment]
Hello, I'm one of the contributors to the theme_tailor package and can tell you that using theme extensions would be very beneficial. When creating complex UI with lots of color it's complicated to stay in the strict borders of Cupertino or Material theme. Your package is great and I understand your philosophy. @jtdLab @GroovinChip
