### ISSUE TITLE
Implement date pickers

### ISSUE THREAD

**Issue by bdlukaa** [macosui/macos_ui#42]
Implement date and hour pickers:

- Graphical pickers

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/datePickerGraphical.png)

- Textual pickers

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/datePickerTextual.png)

Resources:
  - [Date Pickers](https://developer.apple.com/design/human-interface-guidelines/macos/selectors/date-pickers/)

[intl](https://pub.dev/packages/intl) should be used to format the dates

**Comment by GroovinChip** [comment]
Closing in favor of #88
