### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by DK3369** [macosui/macos_ui#438]
The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.

**Comment by savdev-ua** [comment]
Having the same issue. I think library code just need to be migrated to the newer version of Flutter. Please ping if there will be any updates

**Comment by savdev-ua** [comment]
@GroovinChip

**Comment by Tobi696** [comment]
Got the same problem...

**Comment by GroovinChip** [comment]
Version 2 beta 1 should resolve this: https://pub.dev/packages/macos_ui/versions/2.0.0-beta.1
