### ISSUE TITLE
Target kernel_snapshot failed: Exception

### ISSUE THREAD

**Issue by baruka99** [macosui/macos_ui#458]
I migrate to the flutter 3.10.5 and dart 3 and got this error while running my project : Target kernel_snapshot failed: Exception

Below you will find the screenshot of the error message I got and the result of my flutter doctor

<img width="1260" alt="Screenshot 2023-07-11 at 16 17 21" src="https://github.com/macosui/macos_ui/assets/60386009/bf917c7a-34d6-48e9-9f09-7c549bdaf03c">
<img width="691" alt="Screenshot 2023-07-11 at 16 19 54" src="https://github.com/macosui/macos_ui/assets/60386009/7564055a-fb83-4690-8414-6dd7b7da5dee">

**Comment by GroovinChip** [comment]
@baruka99 try using the beta version of `macos_ui`.

**Comment by baruka99** [comment]
I have done it before sending the issue but the problem persists !

Below you will see the implementation

![code](https://github.com/macosui/macos_ui/assets/60386009/84510df6-3366-4272-87c9-e3306fef1f27)
