### ISSUE TITLE
`CapacityIndicator` documentation images are not found

### ISSUE THREAD

**Issue by TahaTesser** [macosui/macos_ui#474]
Go to https://pub.dev/documentation/macos_ui/latest/macos_ui/CapacityIndicator-class.html

![image](https://github.com/macosui/macos_ui/assets/48603081/27c4a9ec-c5bf-4fa2-aca1-4f4b4cc14939)

source: https://github.com/macosui/macos_ui/blob/dev/lib/src/indicators/capacity_indicators.dart

**Comment by GroovinChip** [comment]
This is fixed in the latest version, 2.0.2.
