### ISSUE TITLE
Native looking osx preference window?

### ISSUE THREAD

**Issue by Jarrodsz** [macosui/macos_ui#480]
![IMG_6698](https://github.com/macosui/macos_ui/assets/90145421/c1a660ce-b0d9-4c18-b8eb-327fc7797dca)

basically i want to build a window like this.
I wondered if such an attempt was already made before diving into it.

**Comment by GroovinChip** [comment]
Hi @Jarrodsz. I apologize for the lateness of this reply.

As of now, this UI is *mostly* achievable; we have sliders, buttons, and menus. We do not yet have tabs like the ones in your screenshot.

More importantly, multi-window is not yet supported in the Flutter framework. There are third-party plugins that do it, but they achieve it through workarounds that prove to be problematic in most use-cases.
