### ISSUE TITLE
Level Indicator not working as expected

### ISSUE THREAD

**Issue by vietz-dev** [macosui/macos_ui#49]
As stated in the description provided by apple the Level Indicator should implement user interaction. Clicking on a bar or sliding over the bar should adjust the value.

<img width="724" alt="Screenshot 2021-04-23 at 22 24 38" src="https://user-images.githubusercontent.com/17956096/115926381-09fa4600-a483-11eb-9ed0-6e52b9988f07.png">

However, as you can see in the following GIF clicking on a bar does not correspond to the correct selected value.

![showcase](https://user-images.githubusercontent.com/17956096/115927608-f64fdf00-a484-11eb-8bc4-e7c09cd4af9b.gif)

As far as I can tell the element you tap on should be selected. 
The sliding is fine but the first click of the slide is registered as tap thus the value changes before the sliding applies. This should be avoided

**Comment by vietz-dev** [comment]
Unfortunately I cannot look into this issue right now (I will attend some exams in the next weeks, therefore I have to study).

**Comment by bdlukaa** [comment]
I can reproduce this in the latest dev.

**Comment by GroovinChip** [comment]
Thanks for reporting this issue @kiesman99, and thank you @bdlukaa for the quick fix!

**Comment by bdlukaa** [comment]
I'll reopen this because it's still reproducible when its size is changed.

**Comment by bdlukaa** [comment]
It's now working:

![](https://user-images.githubusercontent.com/45696119/118336955-1f461b80-b4e9-11eb-969f-b6245d600a43.gif)
