### ISSUE TITLE
Contextual menu

### ISSUE THREAD

**Issue by aloisdeniel** [macosui/macos_ui#53]
These kinds of menus are almost everywhere in macOS UIs :

![image](https://user-images.githubusercontent.com/7687231/116395370-54cde200-a824-11eb-94a8-f1c481dce62d.png)

Implementing them would require a native plugin since they can appear outside of the main window.

They would also allow to implement list pickers like : 

![image](https://user-images.githubusercontent.com/7687231/116395535-89419e00-a824-11eb-85af-7a5d83777d9a.png)

![image](https://user-images.githubusercontent.com/7687231/116395567-91014280-a824-11eb-94d3-9b6c2de7f19c.png)

[More info](https://developer.apple.com/design/human-interface-guidelines/macos/menus/contextual-menus/)

**Comment by GroovinChip** [comment]
Closing in favor of #89 since more is happening there

**Comment by GroovinChip** [comment]
Closing in favor of #89
