### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yeyutinglou2** [macosui/macos_ui#542]
macos_ui-2.1.4/lib/src/dialogs/macos_alert_dialog.dart:261:47: Error: The getter 'r' isn't defined for the class 'Color'.

**Comment by Adrian-Samoticha** [comment]
I believe the `r`, `g`, and `b` getters were introduced in Flutter 3.27.0. Are you running the latest version of Flutter?

**Comment by yeyutinglou2** [comment]
> I believe the `r`, `g`, and `b` getters were introduced in Flutter 3.27.0. Are you running the latest version of Flutter?

oh，thanks，I'm going to try it out with the latest version。
