### ISSUE TITLE
Implement tooltip

### ISSUE THREAD

**Issue by bdlukaa** [macosui/macos_ui#64]
https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/help#help-tags-tooltips

Help tags, often referred to as tooltips, succinctly describe how to use controls without shifting people’s focus away from the primary interface. Help tags appear when the user positions the pointer over a control for a few seconds.

A help tag remains visible for 10 seconds, or until the pointer moves away from the control.

The tooltips should be rendered according to the pointer (mouse) position, not to its child.

![Tooltip Example](https://developer.apple.com/design/human-interface-guidelines/macos/images/help_Tooltip.png)

**Comment by GroovinChip** [comment]
Big Sur tooltip image:
![Screenshot_20210509-173709_Chrome.jpg](https://user-images.githubusercontent.com/4250470/117587720-4073ca00-b0ed-11eb-9e73-8d4a77b12a5a.jpg)
