### ISSUE TITLE
Implement GradientButton

### ISSUE THREAD

**Issue by harshvsb1105** [macosui/macos_ui#69]
Implementing gradient button

**Comment by GroovinChip** [comment]
Not part of the Big Sur kit

**Comment by macwilko** [comment]
Are there any plans to implement a button like these? 

Thankyou so much, I'm building an app using macos_ui for Flutter, great work so far!

<img width="853" alt="Screenshot 2023-05-25 at 11 36 29" src="https://github.com/macosui/macos_ui/assets/19474610/beb698f9-4a1b-41eb-8345-b06951bab59d">
