### ISSUE TITLE
`MacosTabView` & `MacosTab`

### ISSUE THREAD

**Issue by bdlukaa** [macosui/macos_ui#70]
https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/tab-views/

A tab view presents multiple mutually exclusive panes of content in the same area. A tab view includes a tabbed control and a content area. Each segment of a tabbed control is known as a tab, and clicking a tab displays its corresponding pane in the content area. Although the amount of content can vary from pane to pane, switching tabs doesn’t change the overall size of the tab view or its parent window.

![TabView Preview](https://developer.apple.com/design/human-interface-guidelines/macos/images/tabViews.png)

| Vertical Tabs | Horizontal Tabs |
| ------------- | ----------------- |
| ![](https://developer.apple.com/design/human-interface-guidelines/macos/images/TabView_Top.png) | ![](https://developer.apple.com/design/human-interface-guidelines/macos/images/TabView_Left.png) |
| ![](https://developer.apple.com/design/human-interface-guidelines/macos/images/TabView_Bottom.png) | ![](https://developer.apple.com/design/human-interface-guidelines/macos/images/TabView_Right.png) |

**Comment by GroovinChip** [comment]
@bdlukaa do you intend to continue working on this?

**Comment by bdlukaa** [comment]
no

**Comment by GroovinChip** [comment]
It is worth noting that the screenshots in this issue are outdated. Please see the Figma kit, linked in the README, for updated images.
