### ISSUE TITLE
PulldownButton

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#86]
<img width="228" alt="Screen Shot 2021-05-13 at 9 32 03 PM" src="https://user-images.githubusercontent.com/4250470/118207440-a97f7880-b432-11eb-9ed9-c66854af8c76.png">
<img width="213" alt="Screen Shot 2021-05-13 at 9 32 12 PM" src="https://user-images.githubusercontent.com/4250470/118207448-af755980-b432-11eb-88ef-a6f4e3e1282f.png">

**Comment by lenniezelk** [comment]
is this issue still available to be worked on? if so I'd be interested in picking this up

**Comment by GroovinChip** [comment]
@lenniezelk yes, this is still available. Are you still interested in working on it?
