### ISSUE TITLE
IconLabel

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#87]
<img width="65" alt="Screen Shot 2021-05-13 at 9 32 37 PM" src="https://user-images.githubusercontent.com/4250470/118207477-bf8d3900-b432-11eb-8a8a-13d85f4b8e32.png">
<img width="65" alt="Screen Shot 2021-05-13 at 9 32 54 PM" src="https://user-images.githubusercontent.com/4250470/118207485-c87e0a80-b432-11eb-973c-21f7004e57f6.png">

**Comment by bdlukaa** [comment]
Maybe related to https://github.com/GroovinChip/macos_ui/issues/61 's label
