### ISSUE TITLE
MacosIcons (?)

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#90]
There are some icons in the Figma kit that do not seem to be part of Flutter's `cupertino_icons` package.

We can either implement them as `MacosIcon`s, or PR them to `cupertino_icons`, or both.
<img width="917" alt="Screen Shot 2021-05-13 at 9 36 44 PM" src="https://user-images.githubusercontent.com/4250470/118207742-51954180-b433-11eb-8fcf-41521ccd0210.png">

https://www.figma.com/file/M6K5L3GK0WJh6pnsASyVeE/macOS-Big-Sur-UI-Kit?node-id=26%3A5

**Comment by bdlukaa** [comment]
I think Cupertino Icons is a complete set of icons. You can check all of them here: https://flutter.github.io/cupertino_icons/
